In [ ]:
%matplotlib inline


Tensors
=======

PyTorch中的Tensors与Torch中的几乎是一样的。

用未初始化的内存创建一个大小（5 x 7）的张量：


In [1]:
import torch
a = torch.empty(5, 7, dtype=torch.float)

初始化一个具有正态分布的double型张量，均值为0，方差为1：



In [2]:
a = torch.randn(5, 7, dtype=torch.double)
print(a)
print(a.size())

tensor([[-0.2900, -1.4229, -2.7230, -1.3463, -0.4546,  0.3415, -0.2096],
        [-1.6002,  0.3603,  0.0391,  1.0323,  1.0186,  0.5080,  0.7860],
        [ 0.0033, -0.5321,  0.8231, -1.9239, -1.6096,  0.9697, -0.2321],
        [-0.8466, -1.6952,  0.1851, -1.2134,  1.0681, -1.2139,  0.5348],
        [-0.5398,  1.6228, -0.0278,  0.0599,  0.3209,  0.8887,  1.5830]], dtype=torch.float64)
torch.Size([5, 7])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size``是一个元组，所以支持同样的操作</p></div>

Inplace / Out-of-place
----------------------

第一个区别是，在tensor上的原地操作（inplace）都有一个 ``_`` 后缀。比如，``add``是非原地的操作（out-of-place），而``add_`` 是原地操作。



In [3]:
a.fill_(3.5)
# a has now been filled with the value 3.5

b = a.add(4.0)
# a is still filled with 3.5
# new tensor b is returned with values 3.5 + 4.0 = 7.5

print(a, b)

tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]], dtype=torch.float64) tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]], dtype=torch.float64)


一些操作比如``narrow``没有inplace版本,有一些操作没有out-of-place版本，例如``fill_`` 。所以``.fill``不存在。

零索引
-------------

另一个区别是张量是零索引的 (在lua中tensors索引开始为1)



In [4]:
b = a[0, 3]  # select 1st row, 4th column from a

Tensors也可以使用Python得切片（slicing）索引。



In [5]:
b = a[:, 3:5]  # 所有行，4-5列。注意：左包含，右不包含

无大小写
---------------

所有的函数不再是大小写拼法。比如``indexAdd``现在改为``index_add_``



In [6]:
x = torch.ones(5, 5)
print(x)

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


In [7]:
z = torch.empty(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)

tensor([[  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.]])


In [13]:
x.index_add_(1, torch.tensor([4, 0], dtype=torch.long), z)
print(x)

tensor([[ 501.,    1.,    1.,    1.,   51.],
        [ 501.,    1.,    1.,    1.,   51.],
        [ 501.,    1.,    1.,    1.,   51.],
        [ 501.,    1.,    1.,    1.,   51.],
        [ 501.,    1.,    1.,    1.,   51.]])
tensor([ 4,  0])


Numpy桥
------------

- 将一个 Torch Tensor转换成一个NumPy矩阵，反之亦然。
- Torch张量和NumPy矩阵将共享它们的底层内存位置，改变一个则会改变另一个。
- CPU上所有的张量，除了char张量外都支持NumPy和Tensor之间的相互转换。

## 将一个 Torch Tensor转换成一个NumPy数组



In [14]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b) 	# see how the numpy array changed in value

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


## 将一个NumPy数组转换成一个Torch Tensor




In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


CPU上所有的Tensor除了CharTensor都支持与Numpy的互相转换

CUDA Tensors
------------

将一个CUDA张量从CPU转移到GPU上，将保留它的底层类型。


In [19]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():

    # creates a LongTensor and transfers it
    # to GPU as torch.cuda.LongTensor
    a = torch.full((10,), 3, device=torch.device("cuda"))
    print(type(a))
    b = a.to(torch.device("cpu"))
    # transfers it to CPU, back to
    # being a torch.LongTensor
    print(type(b))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
